#!/usr/bin/env bash

IMAGE=dkarlovi/php-toolbox
TAG=latest

# ensure Compose cache folder exists before running docker run
# this avoids having Docker creating it as root user
mkdir -p "${HOME}/.composer/cache"

tty=
tty -s && tty=--tty

docker run --rm ${tty} --interactive \
    --user "$(id -u):$(id -g)" \
    --volume "${HOME}/.composer:/composer" \
    --volume "$(pwd):/app" \
    "${IMAGE}:${TAG}" ${@}
